version: "3.7"

services:
  digitalife-myql:
    container_name: myql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data:/var/lib/mysql